export enum FailureType {
  REPLAY_PARITY_FAILURE = 'REPLAY_PARITY_FAILURE',
  SCHEDULER_PARITY_FAILURE = 'SCHEDULER_PARITY_FAILURE',
  RUNTIME_STATE_MISMATCH = 'RUNTIME_STATE_MISMATCH',
  IDENTITY_IPA_MISMATCH = 'IDENTITY_IPA_MISMATCH',
  CERTIFICATION_CLOSURE_FAILURE = 'CERTIFICATION_CLOSURE_FAILURE',
  LEDGER_INTEGRITY_FAILURE = 'LEDGER_INTEGRITY_FAILURE',
  VERSION_LOCK_MISMATCH = 'VERSION_LOCK_MISMATCH',
  SCHEMA_VALIDATION_FAILURE = 'SCHEMA_VALIDATION_FAILURE',
  TRACE_DESERIALIZATION_FAILURE = 'TRACE_DESERIALIZATION_FAILURE',
  FACADE_INTEGRITY_VIOLATION = 'FACADE_INTEGRITY_VIOLATION',
  UNKNOWN_DETERMINISTIC_FAILURE = 'UNKNOWN_DETERMINISTIC_FAILURE'
}

export type DeterministicFailure = {
  failureType: FailureType;
  executionId?: string;
  replayId?: string;
  certificationId?: string;
  ledgerEntryId?: string;
  message: string;
  deterministic: true;
};
